# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: qdsp
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile.travis
    - GH_REPO_REF: github.com/matt2718/qdsp.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - echo 'Building stuff'

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x docDeploy.sh
  - ./docDeploy.sh
